- public/dockerfiles/mongodb-agent/107.0.13.8702-1_1.0.1/ubi/Dockerfile
- public/dockerfiles/mongodb-agent/107.0.15.8741-1_1.0.1/ubi/Dockerfile
- public/dockerfiles/mongodb-agent/108.0.4.8770-1_1.0.1/ubi/Dockerfile
- public/dockerfiles/mongodb-agent/108.0.6.8796-1_1.0.1/ubi/Dockerfile
- public/dockerfiles/mongodb-agent/108.0.7.8810-1/ubi/Dockerfile
- public/dockerfiles/mongodb-agent/108.0.7.8810-1_1.0.0/ubi/Dockerfile
- public/dockerfiles/mongodb-agent/108.0.7.8810-1_1.0.1/ubi/Dockerfile
- public/dockerfiles/mongodb-agent/12.0.33.7866-1_1.0.1/ubi/Dockerfile
- public/dockerfiles/mongodb-agent/12.0.34.7888-1_1.0.1/ubi/Dockerfile
- public/dockerfiles/mongodb-agent/12.0.35.7911-1_1.0.1/ubi/Dockerfile
- public/dockerfiles/mongodb-agent/13.34.0.9465-1/ubi/Dockerfile
- public/dockerfiles/mongodb-agent/13.34.0.9465-1_1.0.0/ubi/Dockerfile
- public/dockerfiles/mongodb-agent/13.34.0.9465-1_1.0.1/ubi/Dockerfile
- public/dockerfiles/mongodb-enterprise-ops-manager/8.0.7/ubi/Dockerfile
- public/dockerfiles/mongodb-kubernetes-database/1.0.1/ubi/Dockerfile
- public/dockerfiles/mongodb-kubernetes-init-appdb/1.0.1/ubi/Dockerfile
- public/dockerfiles/mongodb-kubernetes-init-database/1.0.1/ubi/Dockerfile
- public/dockerfiles/mongodb-kubernetes-init-ops-manager/1.0.1/ubi/Dockerfile
- public/dockerfiles/mongodb-kubernetes/1.0.1/ubi/Dockerfile
Sync dockerfiles after release of `1.0.1` version
Not needed.
> Sync dockerfiles after taging 1.0.1

- RELEASE_NOTES.md
- public/.evergreen.yml
Missing release notes + goreleaser fix/todo
No changes in the code. `goreleaser` was successfully tested during release
> Missing release notes + goreleaser fix/todo

- main.go
- pkg/pprof/pprof.go
- pkg/pprof/pprof_test.go
- pkg/util/constants.go
pprof can be configured by two new environment variables:
- `MDB_OPERATOR_PPROF_ENABLED` - together with `OPERATOR_ENV` controls enabling of pprof server. Basically the rule for enabling pprof is defined in `IsPprofEnabled` function: https://github.com/mongodb/mongodb-kubernetes/blob/94fc9eac3f36cc7df096e86b5eef8ce9fed02f58/pkg/pprof/pprof.go#L66-L70
- `MDB_OPERATOR_PPROF_PORT` - by default it is set to 10081
It's more than `_ "net/http/pprof"` one liner for a couple of reasons:
- having the possibility to enable pprof for the production environment is necessary for debugging memory issues and it does not add much overhead either https://stackoverflow.com/a/64057856. Previously it was only enabled for dev and local
- exposing by default pprof server in production is a no-go in many …
> CLOUDP-317911 Add pprof integration in operator

- scripts/dev/configure_docker_auth.sh
Fix unbound variable in bash script
Script works when env var is not set
> Fix unbound variable in bash script

- .evergreen-tasks.yml
- docker/mongodb-kubernetes-tests/tests/olm/olm_operator_upgrade.py
- docker/mongodb-kubernetes-tests/tests/olm/olm_operator_upgrade_with_resources.py
- scripts/evergreen/operator-sdk/prepare-openshift-bundles-for-e2e.sh
- scripts/evergreen/release/update_release.py
Replaces #91
Now that we have MCK 1.0.0 artifacts out, this pull request removes conditional logic that was previously gated by the release of version 1.0.0.
CI must be green
> CLOUDP-310820: Resolve post 1.0.0 to do items

- PIPELINE.md
- pipeline.py
- Add documentation for pipeline.py
- Add env variables documentation used by `pipeline.py` for easier references.
- Some docs were in wrong locations, likely merging errors. I've looked into the history and moved the to their original locations.
> Add documentation for pipeline.py

- lib/sonar/builders/docker.py
CLOUDP-318984: Print image digest SHA256 in build logs
```
[2025/05/15 10:18:10.029] INFO     2025-05-15 08:18:10,028 [docker]  path: .
[2025/05/15 10:18:10.029] INFO     2025-05-15 08:18:10,029 [docker]  dockerfile: /data/mci/29b9d13cde870de4a9f51dadb28d48e9/tmp/tmpczprlyge
[2025/05/15 10:18:10.029] INFO     2025-05-15 08:18:10,029 [docker]  tag: sonar-docker-build-9574
[2025/05/15 10:18:10.029] INFO     2025-05-15 08:18:10,029 [docker]  buildargs: {'imagebase': '268558157000.dkr.ecr.us-east-1.amazonaws.com/dev/ops-manager-context:6825a2b7cba4af0007d7845c'}
[2025/05/15 10:18:10.029] INFO     2025-05-15 08:18:10,029 [docker]  labels: {}
[2025/05/15 10:18:10.029] INFO     2025-05-15 08:18:10,029 [docker]  executing cli docker build: docker buildx build --load --progress plain . -f …
```
> CLOUDP-318984: Print image digest SHA256 in build logs

- scripts/dev/configure_docker_auth.sh
`configure_docker_auth.sh` should only try to skip logging in when not running on Evergreen, according to its comments, but the shell script condition was inverted to only enable the early exit on Evergreen, not locally.
This now causes issues on Evergreen where preceding runs might have left stale quay.io registry credentials. Always configuring docker auth on CI ensures that our credentials override any stale ones.
No CI tasks output `Docker credentials are up to date - not performing the new login!`.
- Remember the following Communication Standards - use comment prefixes …
> Fix configure_docker_auth Evergreen credentials caching

- scripts/dev/configure_docker_auth.sh
`configure_docker_auth.sh` should only try to skip logging in when not running on Evergreen, according to its comments, but the shell script condition was inverted to only enable the early exit on Evergreen, not locally.
This now causes issues on Evergreen where preceding runs might have left stale quay.io registry credentials. Always configuring docker auth on CI ensures that our credentials override any stale ones.
No CI tasks output `Docker credentials are up to date - not performing the new login!`.
- Remember the following Communication Standards - use comment prefixes …
> Cherry-pick: Fix configure_docker_auth Evergreen credentials caching (#137)

- controllers/operator/construct/appdb_construction.go
- controllers/operator/construct/database_construction.go
All our init images have been renamed from mongodb-enterprise- to mongodb-kubernetes-
There was a mistake in
`controllers/operator/construct/appdb_construction.go`
---------
> Cherry-pick: Rename init container (#64)

- .evergreen.yml
The EVG `quay_login` step is overriding the credentials required for building the bundle with all the images.
Successful patch: https://spruce.mongodb.com/version/682ebab0a50ac10007169b43
> Skip quay login when building OpenShift bundles

- config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
- docs/mongodbcommunity/users.md
- helm_chart/crds/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
- mongodb-community-operator/api/v1/mongodbcommunity_types.go
- mongodb-community-operator/api/v1/zz_generated.deepcopy.go
- mongodb-community-operator/controllers/mongodb_users.go
- mongodb-community-operator/controllers/replicaset_controller_test.go
- mongodb-community-operator/pkg/authentication/authtypes/authtypes.go
- mongodb-community-operator/pkg/kube/secret/secret_builder.go
- mongodb-community-operator/test/e2e/mongodbtests/mongodbtests.go
- mongodb-community-operator/test/e2e/replica_set_connection_string_options/replica_set_connection_string_options_test.go
- public/crds.yaml
Fixes https://github.com/mongodb/mongodb-kubernetes-operator/issues/1522.
This is a port of https://github.com/mongodb/mongodb-kubernetes-operator/pull/1582.
In this PR, I've added the ability to add custom annotations to the generated connection string secrets in MongoDB Community Operator.
This is useful to handle more deployment scenarios, in particular, scenarios where the operator is not deployed cluster-wide, but to a specific namespace. In these scenarios, the `connectionStringSecretNamespace` property becomes useless because, as stated in the [Kubernetes docs](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#owners-dependents), cross-namespace owner references are disallowed, thus allowing for the secrets to be immediately garbage-collected, as stated in …
> feat: add connection string secret annotations

- .github/CODEOWNERS
Based on discussion in slack thread we are removing @dan-mckean and @vinilage form /helm-chart/crds/ codeowners. This means engineers will need to explicitly ask them to review API changes in PRs - if that is necessary and @dan-mckean or @vinilage aren't already aware of the changes through other means.
No need for PoW. CODEOWNERS file just needs to be valid.
* **q**: Clarifying …
> [CODEOWNERS] Remove @dan-mckean @vinilage from helm_chart/crds/

- mongodb-community-operator/controllers/validation/validation.go
During validation, users without the scramCredentialsSecretName parameter are [added](https://github.com/mongodb/mongodb-kubernetes/blob/7fa6687dd12bc523f6d5df834672c849b1b737ed/mongodb-community-operator/controllers/validation/validation.go#L95) to a dictionary with an empty key, which leads to the error mentioned in issue #122.
Closes #122
* **nit**: …
> Ignore X.509 users in scram secret collision validation

- RELEASE_NOTES.md
Release notes for OIDC integration.
> [OIDC] Release notes

- scripts/evergreen/release/helm_files_handler.py
- scripts/evergreen/release/update_helm_values_files.py
This pull request includes updates to improve YAML file handling and fixes a minor issue in the `update_standalone` function. The most important changes are grouped below:
* [`scripts/evergreen/release/helm_files_handler.py`](diffhunk://#diff-3e4bf7eb043336f19b2029c2f2b0c2d3497902c0b116255fc99fe6467ae1e453R81): Added a new configuration to set the YAML line width to 4096 in the `update_standalone_installer` function to prevent inconsistent line wrapping in the CI and locally
* [`scripts/evergreen/release/update_helm_values_files.py`](diffhunk://#diff-362db66ba4c033cb3e6d12456bb89ac5782882ffc6f393e8f7d8d36b69aee0ffL60-R62): Fixed the `update_standalone` function by removing trailing commas, which were causing unintended behavior when calling the `update_standalone_installer` function …
> remove trailing commas and set consistent yaml width

- .githooks/pre-commit
- Makefile
- scripts/dev/contexts/evg-private-context
- scripts/dev/contexts/private-context-template
Running pre-commit commands in parallel to speed it up. 
To get the quickest run, execute it locally with skipping license check. Consider putting `export MDB_UPDATE_LICENSES=true` into your `private-context` to always enable generating licenses in pre-commit
**Changes**
- `make precommit` is no longer using EVERGREEN_MODE=true, and is skipping generating licenses by default
- added `make precommit-with-licenses` for easier precommit with generating license step
| Scenario                         | Master Run | PR Run    | Speedup      |
| :------------------------------- | :--------: | :-------: | :----------: |
| **No Cache, With Licenses** |  47.519s   |  31.897s  | 1.49x faster |
| **With Cache, With Licenses** |  24.382s   |  17.291s  | 1.41x faster |
| **No Cache, Without Licenses** …
> Running pre-commit in parallel

- scripts/dev/install_csi_driver.sh
This removes unnecessary bash debug switch in install_csi_driver.sh and aligns it to the standard `set -Eeou pipefail` preamble we use in all shell scripts.
> Remove set -x in install_csi_driver.sh

- README.md
Fix wrong "guidance in this repository" link in readme.
This was reported by the community: https://github.com/mongodb/mongodb-kubernetes/issues/180
> Fix wrong link "guidance in this repository" - Github issue #180

- docker/mongodb-kubernetes-tests/tests/multicluster/multi_cluster_replica_set_scale_up.py
The E2E test `e2e_multi_cluster_replica_set_scale_up` has been flaky and @lucian-tosa suggested that we should fix it. It has been failing while waiting for statefulsets (STSs) to have correct number of in case multi cluster mongoDB deployment. And the problem was sometimes after the `MongoDBMultiCluster (mdbmc)` resource got into running phase (that would mean all the STSs are ready), some of the STSs got into not ready state.
When we see that `mdbmc` resource is Running we try to make sure that STSs have correct number of replicas but because of above problem (STSs transitioning into not ready state from ready), STS didn't have the correct number of replicas and tests failed.
The reason why STS was transitioning into not ready state from ready is, the pod that it was maintaining did the …
> Fix flakiness in the E2E test `e2e_multi_cluster_replica_set_scale_up`

- main.go
- pkg/util/constants.go
- pkg/webhook/setup.go
No need to hardcode operator name as we can determine it from the env var we already pass to the operator.
CI must be green.
> Use operator name from env var for webhook setup

- config/rbac/operator-roles.yaml
- helm_chart/templates/operator-roles.yaml
Helm doesn't render telemetry `ClusterRole` if webhook RBAC is not rendered due to one of the conditions.
Testing with the following commands:
1. Webhook RBAC disabled
```bash
helm template --show-only \
templates/operator-roles.yaml \
./helm_chart \
--namespace mongodb \
--set operator.webhook.registerConfiguration=false \
--set operator.telemetry.enabled=true \
--set operator.telemetry.installClusterRole=true \
| yq 'select((.kind == "ClusterRoleBinding" or .kind == "ClusterRole") and (.metadata.name | contains("telemetry")))'
```
2. Webhook RBAC enabled
```bash
helm template --show-only \
templates/operator-roles.yaml \
./helm_chart \
--namespace mongodb \
--set operator.webhook.registerConfiguration=true \
--set operator.telemetry.enabled=true \
--set …
```
> Fix YAML document separator in operator RBAC

- .evergreen-periodic-builds.yaml
- we've added more operator versions
- in the past we split up the work but didn't have had the time to dynamically split them up
- splitting them up here to run periodic builds for all agents 
[build_2](https://spruce.mongodb.com/task/mongodb_kubernetes_periodic_build_periodic_build_agent_2_patch_27640f974c9defa062d9b762351f93e3d7298d9c_6870fae614672d0007394e63_25_07_11_11_52_07/logs?execution=0)
[build_3](https://spruce.mongodb.com/version/6870fcded362490007ec8fb1/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
- Remember the following Communication Standards - use comment …
> fix periodic builds for ssdlc

- .githooks/pre-commit
- config/rbac/kustomization.yaml
- config/rbac/operator-roles-base.yaml
- config/rbac/operator-roles-pvc-resize.yaml
- helm_chart/templates/operator-roles-base.yaml
- helm_chart/templates/operator-roles-pvc-resize.yaml
- public/mongodb-kubernetes-multi-cluster.yaml
- public/mongodb-kubernetes-openshift.yaml
- public/mongodb-kubernetes.yaml
In https://github.com/mongodb/mongodb-kubernetes/pull/258 I split existing roles into separate files: base RBAC, telemetry, webhook and `clustermongodbroles` related RBAC.
In this iteration we split basic role further. We separate PVC resize permissions into a separate role.
CI must be green.
* **note**: Side-note, …
> CLOUDP-331496: Split operator roles into smaller templates: split base role

- controllers/operator/mongodbsearch_controller_test.go
- controllers/search_controller/mongodbsearch_reconcile_helper.go
- controllers/search_controller/search_construction.go
- helm_chart/values.yaml
- mongodb-community-operator/pkg/mongot/mongot_config.go
- scripts/dev/contexts/e2e_mdb_community
This reverts handling replicaSetName from mongot config and adds passing all mongod hosts in the connection string.
It is not necessary now to set it, as mongot is connecting in a replicaset mode when there is more than one host passed on connection string.
* PR #229:
`master` ← `search/public-preview`
* **PR #273 (THIS ONE)**:
`search/public-preview` ← `lsierant/search-multiple-hosts`
> Reverted replicaSetName in favor of putting more hosts in connection string

- scripts/release/kubectl-mongodb/install_istio_separate_network.sh
- scripts/release/kubectl-mongodb/sign.sh
- scripts/release/kubectl-mongodb/verify.sh
This RP fixes the shellcheck (info) issues that we saw in the `kubectl-mongodb` plugin related scripts when we ran `make precommit`.
Most of the issues are fixed when I didn't actually have to make any change but I had to disable check for some lines where it was expected to make some change and I was not sure if that would impact things functionally. 
NA
> Fix shellcheck issues in the kubectl-mongodb plugin scripts

- scripts/funcs/multicluster
When we change the directory of `kubectl-mongodb` from `public/tools/multicluster` to `cmd/kubectl-mongodb` we change the source file `build_multi_cluster_kubeconfig_creator.sh` to use the new path but I missed updating the new path in the file `funcs/multicluster`. This PR fixes that problem and updates the path to point to the correct location.
Run `make prepare_local_e2e`, that will build the `kubectl-mongodb` binary and use the `kubectl mongodb multicluster` command to setup the multicluster environment. 
> Correct `kubectl-mongodb` path for command `prepare_local_e2e`

- .evergreen-functions.yml
- .evergreen-periodic-builds.yaml
- .evergreen.yml
- when refactoring and removing daily builds we also removed parts of teardown by accident 
- periodic getting triggered: https://spruce.mongodb.com/version/689dc0de0e8148000791e683/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> fix periodic teardowns

- .evergreen-functions.yml
- .evergreen.yml
- build_info.json
- scripts/release/build/build_info.py
- scripts/release/build/build_scenario.py
- scripts/release/pipeline_main.py
- scripts/release/tests/build_info_test.py
Add a new `manual_release` scenario to properly handle image releases that are decoupled from operator releases.
Tested `release_agent` task on Evergreen, manually edited json file to point to my repo, and added `--all-agents` ton actually trigger a release.
Task:
https://spruce.mongodb.com/task/mongodb_kubernetes_release_agent_release_agent_patch_cda9f730105c7b461ebb9a5fcf6adfea66006d35_68a5c140eba83800072c1894_25_08_20_12_36_23/logs?execution=0
Agents were pushed to my private repository.
- [ X ] Have you checked whether your jira ticket required DOCSP changes?
- [ X ] Have you added changelog file?
- refer to [Changelog files and Release Notes](https://github.com/mongodb/mongodb-kubernetes/blob/master/CONTRIBUTING.md#changelog-files-and-release …
> Agent and OM releases with new pipeline

- .evergreen.yml
This pull request updates the build configuration to include the "cloudqa" tag for several multi-cluster end-to-end (E2E) test variants in `.evergreen.yml`. This allows these test suites to be more easily identified and filtered as part of cloud QA processes.
Build configuration updates:
* Added the "cloudqa" tag to the `tags` list for the following build variants in `.evergreen.yml`:
- `e2e_multi_cluster_kind`
- `e2e_static_multi_cluster_kind`
- `e2e_multi_cluster_2_clusters`
- `e2e_static_multi_cluster_2_clusters`
- ci is starting
- evergreen is parsed
- refer to [Changelog files and Release Notes](https://github.com/mongodb/mongodb-kubernetes/blob/master/CONTRIBUTING.md#changelog-files-and-release-notes) section in CONTRIBUTING.md for more …
> add multicluster to cloudqa bump tests

- .githooks/pre-commit
- scripts/dev/recreate_python_venv.sh
- scripts/dev/switch_context.sh
- scripts/evergreen/build_multi_cluster_kubeconfig_creator.sh
- scripts/evergreen/e2e/build_tests_image_ibm.sh
- scripts/evergreen/setup_aws.sh
- scripts/evergreen/setup_kind.sh
- scripts/evergreen/setup_kubectl.sh
- scripts/minikube/setup_minikube.sh
This pull request focuses on improving shell script robustness and consistency across the codebase. The most significant change is an enhancement to the pre-commit hook's `shellcheck` integration, which now attempts to auto-fix issues and provides a clearer summary of failures. 
**Shellcheck automation and reporting:**
* Enhanced the `.githooks/pre-commit` script to attempt auto-fixing shellcheck issues, collect failed files, and display a summary of failures instead of exiting on the first error. This improves developer experience and code quality.
* We will not print each file we check, that is not useful information. Only print if we fixed one or were unable to fix it automatically
- running `make precommit` locally - failing:
```
update_jobs: user       0m0.053s
update_jobs: sys …
```
> fix shellcheck and auto fix

- docker/mongodb-agent/Dockerfile.atomic
- docker/mongodb-kubernetes-init-database/content/agent-launcher.sh
This PR fixes an issue with the new agent dockerfiles where the db tools where not placed correctly. The binaries should be present in `/tools`. However, our tests were still passing. For that reason, the agent-script will now fail if the binaries are missing.
The tests should fail if the binaries are missing. Example: https://spruce.mongodb.com/version/68af05cace35b000077fae05/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
The pipeline should pass.
> Fix tools in agent images

- release.json
Change the tools_version for OM 8.0.4 in release.json. Both 8.0.4 and 8.0.5 used the same agent version but with different tools versions. This meant that the pipeline for building the agents was rebuilding the same tag twice with different tools versions. This way we don't rebuild the same tag twice, while keeping 8.0.4 in release.json for clarity.
CI is green
> Change OM 8.0.4 from release.json

- config/manager/manager.yaml
- helm_chart/values.yaml
- public/mongodb-kubernetes-multi-cluster.yaml
- public/mongodb-kubernetes-openshift.yaml
- public/mongodb-kubernetes.yaml
- release.json
Bump the default agent version used for AppDB to match the latest OM release.
CI Passing should be sufficient.
> CLOUDP-339183: Update default agent version (used for AppDB)

- controllers/operator/construct/database_construction.go
- pkg/statefulset/statefulset_util.go
This piece of code is meant to preserve cert hash annotation in the pod template. We currently do not use cert hash annotation on the pod: we only use sts level annotations.
Tests must pass
> CLOUDP-290847: Remove outdated code

- .evergreen-functions.yml
- docker/mongodb-kubernetes-tests/kubetester/mongodb_utils_state.py
- docker/mongodb-kubernetes-tests/kubetester/mongotester.py
- docker/mongodb-kubernetes-tests/kubetester/opsmanager.py
- docker/mongodb-kubernetes-tests/tests/authentication/sharded_cluster_x509_to_scram_transition.py
- docker/mongodb-kubernetes-tests/tests/conftest.py
fixes:
* e2e_sharded_cluster_scram_sha_256_user_connectivity 
* e2e_replica_set_scram_sha_256_user_connectivity 
both were mostly failing on master merges on openshift.
PoW shows 3x passing in a row each one
**Reliability improvements for authentication tests:**
* Added a `_wait_for_mongodbuser_reconciliation` function to ensure all `MongoDBUser` resources reach the "Updated" phase before authentication attempts, preventing race conditions after user/password changes. This function is now called at the start of all authentication assertion methods
* Increased the default number of authentication attempts 50 across all relevant methods
* Some of the tests and their logs showed that we are updating the secret and sometimes the reconcile is slow to pick them up. In the meantime we already …
> CLOUDP-316922 - Fix racy and slow auth tests like in openshift clusters

- scripts/evergreen/check_precommit.sh
If we (MCK) started consuming a new go mod deps and because of that we would need to regenerate (`update_licenses.sh`) the `LICENSE-THIRD-PARTY` file for the main project as well as `kubectl-mongodb` plugin. If we forget doing that, the CI would fail with below error
```
We have files that differ after running pre-commit, please run the pre-commit locally
```
and running `pre-commit` doesn't really update the licenses file, to do that, we will have to run `make precommit-with-licenses`. And that's why this PR updates above message.
NA
> Improve the message in `check_precommit.sh` for go mod licenses case

- docker/mongodb-kubernetes-tests/tests/multicluster/multi_cluster_replica_set_migration.py
- scripts/dev/setup_kind_cluster.sh
- scripts/evergreen/setup_kind.sh
As part of the release process, we update the kind and `kindest/node` to latest available versions. This PR does that.
On EVG environments the script `setup_kind_cluster.sh` tries to pull the image from the ecr mirror instead of pulling it from docker hub to avoid rate limiting issues. That's why to make sure that CI passes on this PR, we will have to copy the image manually to the ecr from docker hub.
Below command can be used to do that
```
docker pull kindest/node:v1.33.2@sha256:c55080dc5be4f2cc242e6966fdf97bb62282e1cd818a28223cf536db8b0fddf4
skopeo copy --preserve-digests --all docker://docker.io/kindest/node:v1.33.2 docker://268558157000.dkr.ecr.eu-west-1.amazonaws.com/docker-hub-mirrors/kindest/node:v1.33.2
```
The index digest on ecr will be same and that's the same digest that can …
> Update `kind` and `kindest/node` image to latest available versions (`1.33.2`)

- changelog/20250902_fix_fix_proxy_environment_variables.md
- docker/mongodb-kubernetes-init-database/content/agent-launcher.sh
- docker/mongodb-kubernetes-tests/tests/operator/operator_proxy.py
This PR fixes a bug where the mongodb agents were not using the `NO_PROXY` environment variable set on the operator. This is an issue with the agent where setting the `httpProxy` flag will ignore the environment variables. Therefore, running the agent without that flag work properly whether the variables are set or not.
To make sure this is tested, the `e2e_operator_proxy` test was updated by adding a `NO_PROXY` variable set to cloud-qa and asserting that the proxy does not intercept those calls.
Ran a [patch](https://spruce.mongodb.com/version/68b6ca1169f9af0007311434/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) where the test was updated, but the fix was not added. It failed, proving that the setting the `NO_PROXY` variable did not work.
With the fix, the CI should be green.
- use …
> CLOUDP-342319 - Fix proxy env vars

- changelog/20250904_fix_fix_individual_agent_container_restarts.md
- docker/mongodb-agent/setup-agent-files.sh
- scripts/evergreen/e2e/dump_diagnostic_information.sh
Adding the `--remove-destination` flag to `cp` in `setup-agent-files.sh` will prevent the agent container from getting stuck whenever the agent or the utilities container is restarted.
If the utilities container is restarted, then the pid of the utilities marker will change. This means that the symlink for the probes are pointing to the filesystem of the old pid, therefore a dangling symlink. When the agent container is restarted, `cp` will not be able to overwrite the symlink without this flag.
This change will require re-releasing all agent images.
Before the change
After the change. The containers are ready even if they were restarted
- refer to [Changelog files and Release Notes](https://github.com/mongodb/mongodb-kubernetes/blob/master/CONTRI …
> CLOUDP-342878 - Add --remove-destination to cp

- build_info.json
- scripts/release/tests/build_info_test.py
I've notices that we had a wrong repository name for ops-manager in `build_info.json` -> `mongodb-enterprise-ops-manager` instead of `mongodb-enterprise-ops-manager-ubi`. If we would run the OM release it would be pushed to the wrong repository where only context files reside.
Passing CI.
> Fix for wrong repository name for ops-manager in `build_info.json`

- .evergreen-release.yml
- .evergreen-tasks.yml
In recent `1.3.0` release some of the tasks didn't start when the github tag was created, namely:
- task_gke_multi_cluster_snippets
- task_gke_multi_cluster_no_mesh_snippets
- build_test_image_for_smoke_tests
- e2e_smoke
- e2e_static_smoke
The reason is (most probably) that the tasks didn't have `allowed_requesters: [ "patch", "github_tag" ]` set, only the **variants** had.
There is no easy way to test this unfortunately. The `allowed_requesters: [ "patch", "github_tag" ]` is the only difference between tasks that started successfully in https://spruce.mongodb.com/version/mongodb_kubernetes_1.3.0_68baae22f7d2690007feb541/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC and those that were missing.
- refer to [Changelog files and Release …
> Add missing `allowed_requesters: [ "github_tag" ]` to release tasks

- docker/mongodb-agent/dummy-probe.sh
- docker/mongodb-agent/dummy-readinessprobe
- docker/mongodb-agent/setup-agent-files.sh
This pull request updates the probe scripts for the MongoDB agent container to dynamically locate and execute the actual probe scripts from the init-database container, instead of relying on static dummy scripts. This improves the reliability of liveness and readiness checks, especially during container startup and init container restarts. Additionally, the old logic for replacing dummy probe scripts with real ones via symlinking has been removed, as it is no longer needed.
**Dynamic probe execution:**
* [`docker/mongodb-agent/dummy-probe.sh`] Replaces the static dummy liveness probe with a dynamic script that locates and executes the real probe from the init-database container using the shared process namespace. 
* [`docker/mongodb-agent/dummy-readinessprobe`] Replaces the static dummy …
> change linking approach with directly running the probes

- api/v1/mdb/mongodb_types.go
- api/v1/search/mongodbsearch_types.go
- config/crd/bases/mongodb.com_mongodbsearch.yaml
- controllers/operator/mongodbsearch_controller_test.go
- controllers/searchcontroller/mongodbsearch_reconcile_helper.go
- docker/mongodb-kubernetes-tests/tests/search/fixtures/search-minimal.yaml
- helm_chart/crds/mongodb.com_mongodbsearch.yaml
- public/crds.yaml
This PR exposes logging configuration of mongot pods to MongoDBSearch CRD. 
> CLOUDP-321073: Handle logLevel in MongoDBSearch

- docker/mongodb-agent/Dockerfile
License files were placed incorrectly in mongodb agent images causing preflights to fail.
> Move licenses to correct dir

- public/dockerfiles/mongodb-agent/107.0.17.8771-1/ubi/Dockerfile
- public/dockerfiles/mongodb-agent/108.0.13.8870-1/ubi/Dockerfile
When preparing for the 1.4.0 release I copied the wrong agent dockerfiles in the public folder, these are the updated multi arch ones.
> Use the right public dockerfiles for the latest agent images

- .github/CODEOWNERS
Automatically add @vinilage as required reviewer for `changelog/` files modification.
no-op
> Add @vinilage to CODEOWNERS of `changelog/` dir

- .evergreen.yml
This pull request introduces a temporary workaround in the `.evergreen.yml` configuration to address an issue with the queryable backup task in OM8. A new task group is added that excludes the problematic task, and the build variant is updated to use this new group until the issue is resolved in [CLOUDP-346008](https://jira.mongodb.org/browse/CLOUDP-346008).
**Task group adjustments:**
* Added a new task group `e2e_ops_manager_kind_5_0_only_task_group_without_queryable_backup` that omits the queryable backup task, as a temporary measure while the OM8 issue is outstanding.
**Build variant updates:**
* Updated the build variant to use the new task group instead of the original, with a clear TODO to revert this once the OM8 issue is fixed.
We still run `e2e_om_ops_manager_queryable_backup` …
> Disable `e2e_om_ops_manager_queryable_backup` in OM8 e2e variant

- api/v1/mdb/mongodb_types.go
- api/v1/mdb/mongodb_types_test.go
- changelog/20250909_feature_improved_agent_certificate_rotation.md
- controllers/om/automation_config_test.go
- controllers/om/backup_agent_config.go
- controllers/om/backup_agent_test.go
- controllers/om/monitoring_agent_config.go
- controllers/operator/appdbreplicaset_controller.go
- controllers/operator/appdbreplicaset_controller_test.go
- controllers/operator/authentication/authentication.go
- controllers/operator/authentication/x509.go
- controllers/operator/authentication_test.go
- controllers/operator/certs/certificates.go
- controllers/operator/clusterchecks_test.go
- controllers/operator/common_controller.go
- controllers/operator/common_controller_test.go
- controllers/operator/construct/database_construction.go
- controllers/operator/database_statefulset_options.go
- controllers/operator/mongodbmultireplicaset_controller.go
- controllers/operator/mongodbreplicaset_controller.go
- controllers/operator/mongodbshardedcluster_controller.go
- controllers/operator/mongodbstandalone_controller.go
- docker/mongodb-kubernetes-tests/tests/tls/tls_x509_configure_all_options_rs.py
- docker/mongodb-kubernetes-tests/tests/tls/tls_x509_configure_all_options_sc.py
- docker/mongodb-kubernetes-tests/tests/users/users_addition_removal.py
- docker/mongodb-kubernetes-tests/tests/vaultintegration/mongodb_deployment_vault.py
- pkg/util/constants.go
- pkg/vault/vault.go
Pods now mount a secret containing both old and new certificates, with file names being the hash of the certificate. When it is time to rotate the certificate, the operator updates the automation config with a new path (including the hash) to the certificate. This eliminates the need to manually restart Pods during certificate rotation.
Other related PRs:
* https://github.com/mongodb/mongodb-kubernetes/pull/383 - removes cert hash annotations, simplifies how we pass cert hashes a bit.
* https://github.com/mongodb/mongodb-kubernetes/pull/378 - clean up around Opaque cert secrets which are no longer supported.
* https://github.com/mongodb/mongodb-kubernetes/pull/371 - preparation refactoring which made implementation of this PR a bit easier).
* …
> CLOUDP-290847: Improve agent certificate rotation

- changelog/20251001_fix_mongodbmulticluster_not_ready_if_0_members.md
- controllers/operator/mongodbmultireplicaset_controller.go
- docker/mongodb-kubernetes-tests/tests/multicluster/multi_cluster_replica_set_scale_down.py
Fixes issue in `MongoDBMultiCluster` not ready if `clusterSpecList` contains 0 members.
Passing CI with new test case where we scale down to 0 members in one cluster.
> CLOUDP-324655 - fix MongoDBMultiCluster not ready if clusterSpecList contains 0 members
